const main = async () => {
  console.log('This ran');
};

main().catch(console.error);



